apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.argocdNamespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.projectName }}
  destination:
    namespace: monitoring
    server: {{ .Values.spec.destination.server }}
  source:
        repoURL: 'https://prometheus-community.github.io/helm-charts'
        chart: kube-prometheus-stack
        targetRevision: 42.2.1
        helm:
          releaseName: prometheus
          skipCrds: true
          values: |
            prometheus:
              ingress:
                enabled: true
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt
                ingressClassName: nginx
                hosts:
                  - prometheus.monitoring.{{ tpl .Values.domain . }}
                path: "/"
                tls:
                  - hosts:
                    - prometheus.monitoring.{{ tpl .Values.domain . }}
                    secretName: prometheus-tls
            grafana:
              ingress:
                enabled: true
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt
                ingressClassName: nginx
                hosts:
                  - grafana.monitoring.{{ tpl .Values.domain . }}
                path: "/"
                tls:
                  - hosts:
                    - grafana.monitoring.{{ tpl .Values.domain . }}
                    secretName: grafana-tls
            alertmanager:
              ingress:
                enabled: true
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt
                ingressClassName: nginx
                hosts:
                  - alertmanager.monitoring.{{ tpl .Values.domain . }}
                path: "/"
                tls:
                  - hosts:
                    - alertmanager.monitoring.{{ tpl .Values.domain . }}
                    secretName: alertmanager-tls

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true